// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yadqhfflphrfdegasbnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZHFoZmZscGhyZmRlZ2FzYm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDY1OTgsImV4cCI6MjA2NDg4MjU5OH0.cHURKGND0CgUg9cxvYSzuF9YsTkVe5BXYbjxRsSJl7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);